# Numpy Practice

### Importing necessary libraries

In [10]:
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp
import pandas as pd


### 1-D Array

In [11]:
a = np.array([1, 3, 5])
b = np.array([2, 4, 6])

print(a)
print(b)

[1 3 5]
[2 4 6]


### How to multiply 2 Matrix element by element?

In [12]:
c = a*b
print(c)

[ 2 12 30]


### 2D array

In [13]:
d2 = np.array([[1,2,3],[3,4,5]])
print(d2)

[[1 2 3]
 [3 4 5]]


### Get dimensions of an array

In [14]:
print(d2.ndim)

2


In [40]:
#change data type of an array
b = np.array([1, 2, 3], dtype='int16')
print('b =', b)

#get data type
print('data type =',b.dtype)

#print per item size of the array
print('each item size =' , b.itemsize)

#print total size (in item number) of array 
print('total item no =', b.size)


b = [1 2 3]
data type = int16
each item size = 2
total item no = 3
total byte size = 6


In [ ]:
#print total size (in byte)
print('total byte size =', b.size * b.itemsize)

#Alternate way to get total size (in byte)
print('total size (byte) =', )

In [23]:
#get shape
print(b.shape)
print(d2.shape)

(3,)
(2, 3)
