# Numpy Practice

### Importing necessary libraries

In [314]:
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp
import pandas as pd


### 1-D Array

In [315]:
a = np.array([1, 3, 5])
b = np.array([2, 4, 6])

print(a)
print(b)

[1 3 5]
[2 4 6]


### How to multiply 2 Matrix element by element?

In [316]:
c = a*b
print(c)

[ 2 12 30]


### 2D array

In [317]:
d2 = np.array([[1,2,3],[3,4,5]])
print(d2)

[[1 2 3]
 [3 4 5]]


### Get dimensions of an array

In [318]:
print(d2.ndim)

2


In [319]:
#change data type of an array
b = np.array([1, 2, 3], dtype='int16')
print('b =', b)

#get data type
print('data type =',b.dtype)

#print per item size of the array
print('each item size =' , b.itemsize)

#print total size (in item number) of array 
print('total item no =', b.size)


b = [1 2 3]
data type = int16
each item size = 2
total item no = 3


In [320]:
#print total size (in byte)
print('total byte size =', b.size * b.itemsize)

#Alternate way to get total size (in byte)
print('total size (byte) =', b.nbytes)

total byte size = 6
total size (byte) = 6


In [321]:
#get shape
print(b.shape)
print(d2.shape)

(3,)
(2, 3)


## Accessing, changing element of array

In [322]:
#2-D array
a = np.array([[1,2,3,4,5,6], [6,5,4,3,2,1], [1,2,3,4,5,6]])
print(a)

[[1 2 3 4 5 6]
 [6 5 4 3 2 1]
 [1 2 3 4 5 6]]


In [323]:
print(a.shape)

(3, 6)


In [324]:
#get a specific element
print(a[1,-6])

6


In [325]:
#get a row
print(a[1,:])

#get a column
print(a[:, 0])

[6 5 4 3 2 1]
[1 6 1]


In [326]:
#loop on index {start: end: increment} -> excluding the end index
print(a[1, 1:5:2])
print(a[1, 1:-2:2])

[5 3]
[5 3]


In [327]:
#modify
a[1,4] = 100
print(a)

a[:,4] = 200
print(a)
a[1, :] = 300

print(a)

[[  1   2   3   4   5   6]
 [  6   5   4   3 100   1]
 [  1   2   3   4   5   6]]
[[  1   2   3   4 200   6]
 [  6   5   4   3 200   1]
 [  1   2   3   4 200   6]]
[[  1   2   3   4 200   6]
 [300 300 300 300 300 300]
 [  1   2   3   4 200   6]]


In [328]:
#3-d array
a = np.array([[[1,2], [2,3]], [[3,4], [4,3]]])
print(a)

[[[1 2]
  [2 3]]

 [[3 4]
  [4 3]]]


In [329]:
# access 3-d
print(a[:,:,1])

[[2 3]
 [4 3]]


### Initializing different type of arrays

In below operation ```np.zeros(5, 5)``` doesn't work because, the second parameter is supposed to be `dtype`. 

In [330]:
#fill with zeros
# z = np.zeros((5, 5, 5))...
z = np.zeros((5, 5))
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [331]:
#fill with ones
ones = np.ones((5, 5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In below cell, ```np.full``` function takes parameter `a.shape` but ```np.full_like``` takes `a` as parameter. 

In [332]:
#fill with other numbers
# full ((shape), value, dtype)
print(a)
print('-----a------')
x = np.full(a.shape, 99)
print(x)
print('------x99-----')

x = np.full_like(a,9)
print(x)
print('------x9-----')


[[[1 2]
  [2 3]]

 [[3 4]
  [4 3]]]
-----a------
[[[99 99]
  [99 99]]

 [[99 99]
  [99 99]]]
------x99-----
[[[9 9]
  [9 9]]

 [[9 9]
  [9 9]]]
------x9-----


`np.random.rand()` doesn't take a `tuple` as parameter. It takes 1 or more integers as `row` and `column` of the array.

In [333]:
# random array
r = np.random.rand(4, 3, 2)
print(r)

[[[0.1927217  0.70030991]
  [0.3205251  0.37029542]
  [0.33227756 0.54374355]]

 [[0.23047124 0.78586622]
  [0.72717666 0.51635906]
  [0.26909859 0.60644676]]

 [[0.0679818  0.59771715]
  [0.14001211 0.59770785]
  [0.76193291 0.66534971]]

 [[0.61783327 0.74175443]
  [0.25135689 0.76335561]
  [0.94655714 0.80716157]]]


As `np.randpm.rand()` doesn't take tuple and `a.shape` returns a tuple, so, `np.random.rand()` can't take `a.shape` as parameter value. So, `np.random.rand(a.shape)` doesn't work. For tuple passing, use `np.random.random_sample((4,3))`

In [334]:
# random array but shape of others
# print(np.random.rand(a.shape)) -> doesn't work

r = np.random.random_sample((4,3)) #it works
rr = np.random.random_sample(a.shape)
print(r)
print('_________________________________')
print(rr)

[[0.9438433  0.87988643 0.85912709]
 [0.10029998 0.78357395 0.48504643]
 [0.73908872 0.39253597 0.398486  ]
 [0.39358327 0.04883552 0.55446959]]
_________________________________
[[[0.13167748 0.4009431 ]
  [0.28720746 0.38185621]]

 [[0.45061794 0.00172017]
  [0.42326739 0.38019697]]]


### Random integer

In [335]:
#array of rand int (starting number, ending number {exclusive}, size = (shape of array))
# ri = np.random.randint(1, -3, size=(3,3)) # won't work
ri = np.random.randint(1, 3, size=(3,3))
print(ri)

[[1 2 1]
 [1 2 2]
 [2 1 2]]


In [336]:
# identity matrix 
I = np.identity(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Repeat an array

In [337]:
# repeat array
arr = np.array([1,2,3])
rp = np.repeat(arr, 3)
print(rp)

[1 1 1 2 2 2 3 3 3]


In [338]:
# repeat array
arr = np.array([[1,2,3]])
rp = np.repeat(arr, 3, axis = 0)
print(rp)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


### Making a specific array
Like this - 
```
1 1 1 1 1
1 0 0 0 1
1 0 9 0 1
1 0 0 0 1
1 1 1 1 1
```

In [339]:
ans = np.ones((5,5), dtype='int64')
print(ans)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [340]:
z = np.zeros((3,3))
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [341]:
ans[1:4, 1:4] = z
print(ans)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Copying arrays need Attention!!!
`=` does pointer assignment.

In [342]:
# xxxxxxxxxxxxxxxxxxxxxxx doesn't work
# = means assignment
a = np.array([1,2,3])
print(a)
b = a
print(b)
b[1] = 99
print(b)
print(a)

[1 2 3]
[1 2 3]
[ 1 99  3]
[ 1 99  3]


In [343]:
a = np.array([1,2,3])
print(a)
b = a.copy()
print(b)
b[1] = 99
print(b)
print(a)

[1 2 3]
[1 2 3]
[ 1 99  3]
[1 2 3]


# Mathematics

In [344]:
a

array([1, 2, 3])

In [345]:
# adds with all elements
a = a + 2
a = a - 2
a

array([1, 2, 3])

In [346]:
b = np.array([[1,2,3], [3,4,5]])
b + 100
b * 100
b / 100

array([[0.01, 0.02, 0.03],
       [0.03, 0.04, 0.05]])

In NumPy, `*` doesn't mean `matrix multiplication`. It's just element by element multiplication.

In [350]:
b = np.array([[1,2,3], [3,4,5]])
b * 100
print(b * 100)

[[1 2 3]
 [3 4 5]]


In [347]:
x = np.array([[1,2,3], [3,4,5]])
y = np.array([100,200, 300])
print(y / x) # it works surprisingly! 
print(x / y)

[[100.         100.         100.        ]
 [ 33.33333333  50.          60.        ]]
[[0.01       0.01       0.01      ]
 [0.03       0.02       0.01666667]]


In [348]:
# power
x ** 2

array([[ 1,  4,  9],
       [ 9, 16, 25]])

In [349]:
# trigonometry
np.sin(x)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [ 0.14112001, -0.7568025 , -0.95892427]])