# Numpy Practice

### Importing necessary libraries

In [87]:
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp
import pandas as pd


### 1-D Array

In [88]:
a = np.array([1, 3, 5])
b = np.array([2, 4, 6])

print(a)
print(b)

[1 3 5]
[2 4 6]


### How to multiply 2 Matrix element by element?

In [89]:
c = a*b
print(c)

[ 2 12 30]


### 2D array

In [90]:
d2 = np.array([[1,2,3],[3,4,5]])
print(d2)

[[1 2 3]
 [3 4 5]]


### Get dimensions of an array

In [91]:
print(d2.ndim)

2


In [92]:
#change data type of an array
b = np.array([1, 2, 3], dtype='int16')
print('b =', b)

#get data type
print('data type =',b.dtype)

#print per item size of the array
print('each item size =' , b.itemsize)

#print total size (in item number) of array 
print('total item no =', b.size)


b = [1 2 3]
data type = int16
each item size = 2
total item no = 3


In [93]:
#print total size (in byte)
print('total byte size =', b.size * b.itemsize)

#Alternate way to get total size (in byte)
print('total size (byte) =', b.nbytes)

total byte size = 6
total size (byte) = 6


In [94]:
#get shape
print(b.shape)
print(d2.shape)

(3,)
(2, 3)


## Accessing, changing element of array

In [95]:
#2-D array
a = np.array([[1,2,3,4,5,6], [6,5,4,3,2,1], [1,2,3,4,5,6]])
print(a)

[[1 2 3 4 5 6]
 [6 5 4 3 2 1]
 [1 2 3 4 5 6]]


In [96]:
print(a.shape)

(3, 6)


In [97]:
#get a specific element
print(a[1,-6])

6


In [98]:
#get a row
print(a[1,:])

#get a column
print(a[:, 0])

[6 5 4 3 2 1]
[1 6 1]


In [99]:
#loop on index {start: end: increment} -> excluding the end index
print(a[1, 1:5:2])
print(a[1, 1:-2:2])

[5 3]
[5 3]


In [104]:
#modify
a[1,4] = 100
print(a)

a[:,4] = 200
print(a)
a[1, :] = 300

print(a)

[[  1   2   3   4 200   6]
 [300 300 300 300 100 300]
 [  1   2   3   4 200   6]]
[[  1   2   3   4 200   6]
 [300 300 300 300 200 300]
 [  1   2   3   4 200   6]]
[[  1   2   3   4 200   6]
 [300 300 300 300 300 300]
 [  1   2   3   4 200   6]]


In [106]:
#3-d array
a = np.array([[[1,2], [2,3]], [[3,4], [4,3]]])
print(a)

[[[1 2]
  [2 3]]

 [[3 4]
  [4 3]]]


In [110]:
# access 3-d
print(a[:,:,1])

[[2 3]
 [4 3]]
